package com.quantumcoinwallet.app.locale;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Cross-platform localization parity test (Android side).
 * <p>Mirrors iOS {@code QuantumCoinWalletTests/EnUsParityTests.swift}.
 * Both sides ship the IDENTICAL English string catalog ({@code en_us.json})
 * except for an explicit, audited allow-list of OS-specific divergences.
 * Drift here is a phishing risk (an attacker can craft a screenshot that
 * looks plausibly cross-platform if the strings disagree) and a test/QA
 * regression vector (acceptance scripts that grep for "Backup to iCloud"
 * suddenly do not match the Android string and tests silently pass).
 * <p>How this test works:
 * <ol>
 *   <li>Both files are parsed by a small line-oriented parser (no Android
 *   {@code org.json} mocking required, same approach as
 *   {@code JsonInteractParityTest}). We collect the {@code "<key>": "<value>"}
 *   pairs inside the {@code langValues} block.</li>
 *   <li>For every key in iOS-langValues, we assert the Android file has
 *   the same key. Missing keys = drift.</li>
 *   <li>For every key in Android-langValues, we assert the iOS file has
 *   the same key. Same direction matters: an Android-only string is
 *   unreachable from any iOS QA path.</li>
 *   <li>For each shared key, we assert the values are byte-identical
 *   UNLESS the key appears in {@link #OS_SPECIFIC_DIVERGENCES} (the
 *   audited allow-list).</li>
 * </ol>
 * <p>The iOS file is snapshotted at
 * {@code app/src/test/resources/locale-snapshots/ios_en_us.json}. The
 * snapshot is regenerated by the {@code :app:syncIosLocale} Gradle task
 * (see {@code app/build.gradle}).
 * <p>Skip-if-missing semantics: tests assume the snapshot is present.
 * In a fresh checkout the snapshot is committed to the repo so the
 * tests run unconditionally; if a developer deletes the snapshot
 * locally the suite fails fast with a clear message rather than
 * silently passing.
 */
public class EnUsParityTest {

     /**
     * Audited OS-specific divergences. Adding to this list requires
     * a security-review tag in the PR.: each
     * entry is paired with the rationale for why the divergence is
     * permanent rather than a TODO.
     */
    private static final Map<String, String> OS_SPECIFIC_DIVERGENCES = new HashMap<>();
    static {
        // "Jailbroken" (iOS) vs "Rooted" (Android): platform-specific
        // jailbreak/root vocabulary is the user-facing term of art on
        // each platform and has no cross-platform equivalent.
        OS_SPECIFIC_DIVERGENCES.put("tamper-jailbreak-banner", "rooted-device-vocabulary");
        OS_SPECIFIC_DIVERGENCES.put("tamper-jailbreak-message", "rooted-device-vocabulary");
        // "App Store" (iOS) vs "Play Store" (Android): platform-store
        // names are user-recognizable. Reinstall guidance must point
        // at the right store widget.
        OS_SPECIFIC_DIVERGENCES.put("tamper-runtime-message", "platform-store-name");
        // "iCloud Backup" + "Finder/iTunes" (iOS) vs "Android Auto
        // Backup" + "Smart Switch / device-to-device transfer"
        // (Android): the on-platform backup facilities are different
        // products with different user-visible names. Both messages
        // are accurate for their platform.
        OS_SPECIFIC_DIVERGENCES.put("backup-description", "platform-cloud-backup-name");
        OS_SPECIFIC_DIVERGENCES.put("backup-encrypted-warning", "platform-cloud-backup-name");
        OS_SPECIFIC_DIVERGENCES.put("backup-submitted-cloud-title", "platform-cloud-backup-name");
        OS_SPECIFIC_DIVERGENCES.put("backup-submitted-cloud-message", "platform-cloud-backup-name");
        OS_SPECIFIC_DIVERGENCES.put("cloud-backup-info", "platform-cloud-backup-name");
    }

    @Test
    public void everyIosKeyExistsOnAndroid() throws Exception {
        Map<String, String> ios = readLangValues(snapshot());
        Map<String, String> android = readLangValues(androidLocale());
        Set<String> missing = new TreeSet<>(ios.keySet());
        missing.removeAll(android.keySet());
        if (!missing.isEmpty()) {
            fail("Android en_us.json is missing iOS langValues keys: "
                    + missing
                    + ". Add them with the Android-flavored translation OR "
                    + "extend the OS_SPECIFIC_DIVERGENCES allow-list.");
        }
    }

    @Test
    public void everyAndroidKeyExistsOnIos() throws Exception {
        Map<String, String> ios = readLangValues(snapshot());
        Map<String, String> android = readLangValues(androidLocale());
        Set<String> missing = new TreeSet<>(android.keySet());
        missing.removeAll(ios.keySet());
        if (!missing.isEmpty()) {
            fail("iOS en_us.json (snapshot) is missing Android langValues keys: "
                    + missing
                    + ". Either add them to iOS or remove them from Android. "
                    + "If the divergence is permanent, extend the "
                    + "OS_SPECIFIC_DIVERGENCES allow-list AND open a follow-up "
                    + "ticket to either de-divergence or document the rationale.");
        }
    }

    @Test
    public void sharedKeysHaveByteIdenticalValuesOrAreOnAllowlist() throws Exception {
        Map<String, String> ios = readLangValues(snapshot());
        Map<String, String> android = readLangValues(androidLocale());
        Set<String> shared = new HashSet<>(ios.keySet());
        shared.retainAll(android.keySet());
        List<String> drifted = new ArrayList<>();
        for (String key : new TreeSet<>(shared)) {
            String i = ios.get(key);
            String a = android.get(key);
            if (i.equals(a)) continue;
            if (OS_SPECIFIC_DIVERGENCES.containsKey(key)) continue;
            drifted.add(key + ": iOS=\"" + i + "\" / Android=\"" + a + "\"");
        }
        if (!drifted.isEmpty()) {
            fail("Cross-platform string drift on " + drifted.size()
                    + " key(s):\n  - " + String.join("\n  - ", drifted)
                    + "\nFix the drift OR extend OS_SPECIFIC_DIVERGENCES "
                    + "with a documented rationale.");
        }
    }

    @Test
    public void iosSnapshotIsPresent() {
        File snap = snapshotPath();
        assertTrue("iOS en_us.json snapshot is missing at " + snap.getAbsolutePath()
                        + ". Run `./gradlew :app:syncIosLocale` to regenerate.",
                snap.exists());
    }

    @Test
    public void allowlistEntriesAreCovered() throws Exception {
        // Each entry in the allow-list MUST exist in at least one of
        // the two files; a stale allow-list entry is a smell that
        // hides actual drift.
        Map<String, String> ios = readLangValues(snapshot());
        Map<String, String> android = readLangValues(androidLocale());
        Set<String> known = new HashSet<>();
        known.addAll(ios.keySet());
        known.addAll(android.keySet());
        List<String> stale = new ArrayList<>();
        for (String key : OS_SPECIFIC_DIVERGENCES.keySet()) {
            if (!known.contains(key)) stale.add(key);
        }
        if (!stale.isEmpty()) {
            fail("Stale entries in OS_SPECIFIC_DIVERGENCES (key not present "
                    + "on either platform): " + stale + ". Remove them.");
        }
    }

    // -------- file IO + parser ---------

    private static String snapshot() throws IOException {
        File f = snapshotPath();
        org.junit.Assume.assumeTrue(
                "iOS en_us.json snapshot missing; run `./gradlew :app:syncIosLocale`.",
                f.exists());
        return new String(Files.readAllBytes(f.toPath()), StandardCharsets.UTF_8);
    }

    private static File snapshotPath() {
        return new File("src/test/resources/locale-snapshots/ios_en_us.json");
    }

    private static String androidLocale() throws IOException {
        File f = new File("src/main/res/raw/en_us.json");
        org.junit.Assume.assumeTrue("Android en_us.json missing.", f.exists());
        return new String(Files.readAllBytes(f.toPath()), StandardCharsets.UTF_8);
    }

     /**
     * Slice the {@code langValues: { ... }} block out of the JSON
     * file with a brace-matching state machine, then extract every
     * top-level {@code "key": "value"} pair. Tolerates trailing
     * commas and nested arrays/objects (which are skipped because
     * we only care about scalar string entries -- arrays / objects
     * are NOT cross-checked for parity at this stage; that is a
     * follow-up).
     */
    static Map<String, String> readLangValues(String src) {
        int start = src.indexOf("\"langValues\"");
        if (start < 0) return new LinkedHashMap<>();
        int braceOpen = src.indexOf('{', start);
        if (braceOpen < 0) return new LinkedHashMap<>();
        int depth = 0;
        int braceClose = -1;
        for (int i = braceOpen; i < src.length(); i++) {
            char c = src.charAt(i);
            if (c == '{') depth++;
            else if (c == '}') {
                depth--;
                if (depth == 0) { braceClose = i; break; }
            }
        }
        if (braceClose < 0) return new LinkedHashMap<>();
        String body = src.substring(braceOpen + 1, braceClose);
        Map<String, String> out = new LinkedHashMap<>();
        // Match top-level "key": "value" pairs. Allow escaped
        // double quotes inside the value via the (?:\\"|[^"])* run.
        Pattern p = Pattern.compile(
                "\"([^\"\\\\]+)\"\\s*:\\s*\"((?:\\\\\"|\\\\\\\\|[^\"])*)\"");
        Matcher m = p.matcher(body);
        while (m.find()) {
            out.put(m.group(1), unescape(m.group(2)));
        }
        return out;
    }

    private static String unescape(String s) {
        StringBuilder b = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\' && i + 1 < s.length()) {
                char n = s.charAt(++i);
                switch (n) {
                    case 'n': b.append('\n'); break;
                    case 't': b.append('\t'); break;
                    case 'r': b.append('\r'); break;
                    case '"': b.append('"'); break;
                    case '\\': b.append('\\'); break;
                    case '/': b.append('/'); break;
                    default: b.append('\\').append(n); break;
                }
            } else {
                b.append(c);
            }
        }
        return b.toString();
    }

    @Test
    public void parser_canRoundTripBasicShapes() {
        // Sanity-check the parser so a regression in this test is
        // independently observable.
        String src = "{\n  \"langValues\": {\n"
                + "    \"hello\": \"world\",\n"
                + "    \"escape\": \"a\\\"b\"\n"
                + "  }\n}";
        Map<String, String> kv = readLangValues(src);
        assertEquals(2, kv.size());
        assertEquals("world", kv.get("hello"));
        assertEquals("a\"b", kv.get("escape"));
    }

    /** Exposed for ad-hoc debugging. */
    static List<String> sortedKeys(Map<String, String> m) {
        return new ArrayList<>(new TreeSet<>(m.keySet()));
    }

    @SuppressWarnings("unused")
    private static String csv(Set<String> s) {
        return String.join(", ", new TreeSet<>(s));
    }

    @SuppressWarnings("unused")
    private static String join(String[] arr) { return Arrays.toString(arr); }
}
